config/routes.rb
Travel::Application.routes.draw do
  root to: 'home#index'

  resource :users
  resource :sessions, only: [:create]
  resources :travel_groups

  get '/signup' => 'users#new', as: 'signup'
  get '/login' => 'sessions#new', as: 'login'
  delete '/logout' => 'sessions#destroy'


  get 'auth/:provider/callback' => 'oauth#create'
  get 'auth/failure' => 'oauth#fail'
  get '/auth/facebook', as: 'facebook_oauth'


  post '/join_group' => "travel_groups#join_group"
  get '/bookings' => "travel_groups#bookings"
  get '/suggestions' => "travel_groups#suggestions"
  post "/cast_vote" => "travel_groups#cast_vote"



  namespace :api do
    get '/users.json' => 'test#index'
  end

end

app/models/excursion.rb
class Excursion < ActiveRecord::Base
  has_many :suggestions
  has_many :travel_groups, through: :suggestions
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :travel_group
  belongs_to :excursion
  has_many :votes
end

app/models/travel_group.rb
class TravelGroup < ActiveRecord::Base
  #TODO: Either create a groupe token or invitation to group
  has_and_belongs_to_many :users
  has_many :suggestions
  has_many :excursions, through: :suggestions

  before_save :generate_name
  geocoded_by :destination
  after_validation :geocode
  before_create :generate_code
  # after_create :find_excursions

  private

    def generate_name
      self.name ||= self.users.first.first_name + " " + self.destination
    end

    def find_excursions
      r = HTTParty.get("https://dev.xola.com/api/experiences\?geo=#{self.latitude},#{self.longitude}")
      json = JSON.parse(r.body)
      p '*' * 1000
      p json["data"].first
    end

    def generate_code
      self.group_code = SecureRandom.hex(3).downcase
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :travel_groups
  has_many :votes




  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, :with => VALID_EMAIL_REGEX
  # validates_format_of :username, :with => /\A\w+\z/, :allow_nil => true, :message => 'can only contain letters, numbers, hyphens, or underscores'
  # validates_length_of :username, :maximum => 16, :message => 'can only be 16 characters long'
  # validates_length_of :username, :minimum => 4, :message => 'has to be atleast 4 characters long'

  before_save :downcase_email
  before_create :create_remember_token

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt token
    Digest::SHA1.hexdigest(token.to_s)
  end

   def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.email = auth.info.email
      user.image = auth.info.image
      user.oauth_token = auth.credentials.token
      user.oath_expires_at = Time.at(auth.credentials.expires_at)
      user.password = user.password_confirmation = SecureRandom.urlsafe_base64
    end
  end

  private
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

    def downcase_email
      self.email = email.downcase
    end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :suggestion
  validates_uniqueness_of :user_id, :scope => :suggestion_id

end

app/controllers/api/test_controller.rb
module Api
  class TestController < ApplicationController
    respond_to :json
    def index
      respond_with User.find(:all)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :signed_in?, :current_user

  def sign_in user
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by_remember_token(remember_token)
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @groups = current_user.travel_groups
    end
  end
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    if user.save
      sign_in user
      flash[:success] = "Successfully logged in with Facebook"
      redirect_to root_path
    else
      fail
    end
  end

  def fail
    flash[:error] = "There was an error. Please try again."
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(user_email)
    if user && user.authenticate(user_password)
      sign_in user
      flash[:notice] = "Successfully logged in"
      redirect_to root_url
    else
      @errors = ["Invalid email/password combination."]
      render :new
    end
  end

  def destroy
    sign_out
    flash[:notice] = "You Hae successfully Logged Out"
    redirect_to root_url
  end

  private
    def user_email
      params[:session][:email].downcase
    end

    def user_password
      params[:session][:password]
    end
end

app/controllers/travel_groups_controller.rb
class TravelGroupsController < ApplicationController
  def new
    @travel_group = TravelGroup.new
  end

  def create
    @travel_group = TravelGroup.new(travel_params)
    @travel_group.users << current_user
    if @travel_group.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @group = TravelGroup.find(params[:id])
    # @bookings = @group.suggestions.select{|s| s.vote_count > 0}
    # @suggestions = @group.suggestions.map do |suggestion|
    #   users = suggestion.votes.map(&:user_id)
    #   suggestion unless users.include?(current_user.id)
    # end
  end

  def suggestions
    group = TravelGroup.find(params["group"])
    suggestions = group.suggestions.map do |suggestion|
      users = suggestion.votes.map(&:user_id)
      suggestion unless users.include?(current_user.id)
    end
    # suggestions = Suggestion.all
  
    render :json => render_to_string(:partial => 'travel_groups/suggestions_list', :locals => {suggestions: suggestions}).to_json

  end

  def bookings
    group = TravelGroup.find(params["group"])
    bookings = group.suggestions.select{|s| s.vote_count > 0}.sort_by(&:vote_count)
    render :json => render_to_string(:partial => 'travel_groups/bookings_list', :locals => {bookings: bookings}).to_json
  end

  def cast_vote
    print "*" * 23
    print params
    suggestion = Suggestion.find(params["suggestion"])
    vote = suggestion.votes.new(user_id: current_user.id, choice: params["choice"] )
    if vote.save
      suggestion.vote_count += vote.choice
      suggestion.save
      render :json => {success: "true", vote: vote.choice}
    else
      render :json => {success: "false"}
    end
  end

  def join_group
    group = TravelGroup.find_by_group_code(params["group_code"])
    if group && !group.users.include?(current_user)
      group.users << current_user
      render :json => render_to_string(:partial => 'travel_groups/group', locals: {:g => group}).to_json
    elsif group && group.users.include?(current_user)
      error = "Already member of group"
      render :json => {test: error}
    else
      error = "Invalid group code"
      render :json => {test: error}
    end
  end

  private

    def travel_params
      params.require(:travel_group).permit(:start_date, :end_date, :destination, :name)

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:notice] = "Welcome to Travel!"
      redirect_to root_path
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  def show
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/travel_groups_helper.rb
module TravelGroupsHelper
end

app/views/home/_dashboard.html.haml
.container

  %ul.links
    %li
      %a{:href => '#', :id => "join_group"}
        = "Join"
    %li
      %a{:href => new_travel_group_path}
        = "Create"
  .join_box
    = form_tag "/join_group", :id => "join_form", :style => "display:none;" do
      = label_tag :group_code, "Group Code"
      = text_field_tag :group_code
      = submit_tag "Join"

  %hr/

  %section.group_lists
    %h2
      Trips
    -@groups.each do |g|
      = render "travel_groups/group", :g => g

:javascript
  $(document).ready(function() {
    $("#join_group").on("click", function(e) {
      e.preventDefault();
      $("#join_form").show();
      $("#join_form").on("submit", function(e) {
        e.preventDefault();
        $("#join_form").hide();
        var data = $(this).serialize();
        $.ajax({
          method: "post",
          url: "/join_group",
          data: data
        }).done(function(response) {
          $(".group_list").append(response);
        });
      });
    });
  });

app/views/home/index.html.haml
=content_for :title, "Travel"

- if current_user
  = render 'dashboard'
- else
  .container
    %h1 WEFUN
    %p
      %span
        Travel Together
      %span
        Plan Together
      %span
        Live Together
    = link_to image_tag("/assets/fbook_icon_btn.png", :border =>0), facebook_oauth_path









  :css
    h1 {
      color: white;
      font-size: 7em;
      font-family: 'Montserrat', sans-serif;
      font-weight: 400;
      margin-bottom: 0;

    }
    p {
      color: white;
      margin-bottom: 50px;
    }

    span {
      margin-right: 20px;
    }

    html {
      background: url("assets/bg1.jpg") no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
    }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = yield(:title)
    <link href='http://fonts.googleapis.com/css?family=Montserrat:700,400' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    -if current_user
      = render :partial => 'shared/nav'
    = yield

app/views/shared/_errors.html.haml
-if @errors
  .login_errors
    - @errors.each do |error|
      %p.error
        = error

app/views/shared/_flash.html.haml
%p.notice= notice
%p.alert= alert

app/views/shared/_nav.html.haml
%nav.navbar
  .nav_div
    .left
      = link_to 'WeFun', root_path, :class => "logo"
    - if signed_in?
      .right
        = link_to 'Logout', logout_path, :method => 'delete'

app/views/travel_groups/_bookings_list.html.haml
%section.group_lists
  - if !bookings.empty?
    - bookings.each do |booking|
      .trip_box
        .inner_container
          = image_tag("/assets/excursions/#{booking.excursion.image_url}")
        .group_info
          %ul
            %li
              = booking.excursion.name
            %li
              = booking.vote_count
            %li
              = booking.excursion.price
  - else
    %p
      = "No Suggestions have been voted on Vote Now"

app/views/travel_groups/_group.html.haml
.trip_box
  .inner_container
    = link_to image_tag("/assets/switz.jpg"), travel_group_path(g)
  .group_info
    %ul
      %li
        = link_to g.name, travel_group_path(g)
      %li
        = g.start_date

app/views/travel_groups/_suggestions_list.html.haml
%ul
  - if !suggestions.compact.empty?
    -suggestions.compact.each do |s|
      %li
        = s.excursion.name
        = link_to 'Like', '#', {:class => 'vote_cast', :data => {:suggestion => s.id, :choice => 1}}
        = link_to 'Dislike', '#',{:class => 'vote_cast', :data => {:suggestion => s.id, :choice => 0}}

app/views/travel_groups/new.html.haml
%script{src:"https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"}
.group_list
  %h1.title
    Create Travel Group
  
  .airline_info
    = form_for @travel_group do |f|
      .date.arrival
        = f.label :start_date, 'Arrival'
        = f.date_field :start_date
      .date.departure
        = f.label :end_date, 'Departure'
        = f.date_field :end_date
      .date
        = f.label :destination, 'Destination'
        = f.text_field :destination, :id => 'searchTextField', :placeholder => 'Enter City', :required => true
  
      %h2.sub_header
        Type of Adventure
        %br
        = f.submit 'Fun', {class: 'type'}
        = f.submit 'Family', {class: 'type'}
        = f.submit 'Touristy', {class: 'type'}
        = f.submit 'Adventure', {class: 'type'}

:javascript
  $(function() {
    var searchInputField = document.getElementById('searchTextField');
    var searchBox = new SearchBox(searchInputField);
  });

app/views/travel_groups/show.html.haml
.container
  %h1
    = @group.name
    = "#{@group.start_date} - #{@group.end_date}"
  %h3
    = "Group Code: #{@group.group_code}"
  %h2
    Adventurers

  - @group.users.each do |u|
    = image_tag u.image

  %h2
    = link_to 'Book', '#', {:id => "book_listener"}
    = link_to 'Vote', '#', {:id => "vote_listener"}

  #display_container




  #vote{:style => "display:none;"}


  #group_id{:data => {:group => @group.id }}



:javascript
  $(document).ready(function() {
    groupListeners.init();
    groupController.bookings();
  });

app/views/users/_user_form.html.haml
= render 'shared/errors'

= form_for @user do |f|
  = f.label :first_name, "First Name"
  %br
  = f.text_field :first_name
  %br
  %br
  = f.label :email
  %br
  = f.text_field :email
  %br
  %br
  = f.label :password, "Password"
  %br
  = f.password_field :password
  %br
  %br
  = f.label :password_confirmation, "Confirm Passowrd"
  %br
  = f.password_field :password_confirmation
  %br

  = f.submit("Submit")

app/views/users/new.html.haml
.form_container
  %h1
    Sign Up
  %p
    Please fill out the form below to create a new account.
  = render 'user_form'
  %p
    = link_to 'back', :back